---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-front
  namespace: test-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formation-front
  template:
    metadata:
      labels:
        app: formation-front
    spec:
      containers:
      - name: formation-front
        image: projetformation_client:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: formation-front-service
  namespace: test-workload
spec:
  selector:
    app: formation-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP


