--- 
- name: Copy dapic.yml to the master node
  copy:
    src: dapic.yml  # Spécifiez le chemin local de votre fichier nginx.yml
    dest: /home/k8sadmin/dapic.yml
    owner: k8sadmin

- name: Apply dapic.yml
  shell: kubectl apply -f /home/k8sadmin/dapic.yml
  environment:
    KUBECONFIG: "/home/k8sadmin/.kube/config"


